CREATE TABLE terminals (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  outlet_id BIGINT,
  user_id BIGINT,
  terminal_name VARCHAR(150) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,
  FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE,
  FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
)