
CREATE TABLE outlets (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  user_id BIGINT,
  email VARCHAR(150),
  phone VARCHAR(15) DEFAULT '',
  phone_type type NOT NULL DEFAULT 'work',
  latitude INTEGER DEFAULT 0,
  longitude INTEGER DEFAULT 0,
  position INTEGER DEFAULT 0,
  city_id INTEGER DEFAULT 0,
  country_id INTEGER DEFAULT 0,
  addr VARCHAR(150) DEFAULT '',
  available BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,
  FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE
)